#!/bin/bash
mkdir issue_$1
cp example/example.py issue_$1/issue_$1.py
cp example/example.sql issue_$1/issue_$1.sql
echo "#$1    post    issue_$1/issue_$1.sql" >> ./TODO
echo "#$1    post    issue_$1/issue_$1.py"  >> ./TODO
